Database initializer
Mario-659/FormulaOneApi pull request #11
Opened 2022-10-29 17:34 UTC by lukaszmichalskii

Prototype of F1API service for updating database automatically without interfering with our system API. For now, used for manual testing and creating an initialization script to the database (see: init.sql file).

From my investigations, it seems to be a pretty big task, blocked by API CRUD features not implemented yet. But still maybe you want to have such prototype in our main repo

2022-10-30 09:56 UTC, Mario-659 requested changes
1. Rebase on main
2. Add new line at the end of file in docker compose
3. I'm not sure about `F1APIJobExecutor`. Right now it just fetches drivers from ergast and prints them, right? Why is it needed? Did you use it to make init.sql by changing what data it should fetch after every run? I think it should fetch all the data at once and convert it into sql if that was your idea. Also as it is just a script you could have used Python and put into `scripts` folder. Right now I don't think this script is needed - it would fetch the latest data which is nice but data won't change much in the next few months, so I wouldn't give high priority to this - maybe add task about creating that script to the backlog? - we could do it later when we would have some spare time left.
4. Having `init.sql` file is good. [Here](https://www.javadevjournal.com/spring-boot/loading-initial-data-with-spring-boot/) is how to use it on initialization of spring (in short just rename it to `import.sql`, put into resources and to make it work change `spring.jpa.hibernate.ddl-auto` to `create`). Then you will there are some constraints errors so right now this file is not working properly. Did you test this? Did it work for you?

2022-10-30 10:33 UTC, Mario-659 commented
Ok, I think I know what you meant with that `F1APIJobExecutor`. You wanted to use that in the future to persist fetched data with Repository classes, right? I think we don't need to fetch data every time we want to run spring. I think that script that would convert fetched data to sql would be better but as I said I don't think is is something we should be working on right now

2022-10-30 12:00 UTC, lukaszmichalskii commented
Yep, by F1APIJobExecutor I mean updating/validating data in the future, for now, it is PoC (proof of concept) of such a feature. Further, when API will be ready this feature is essential because of one requirement needed in Software Engineering classes. 

**- Did you test this? Did it work for you?**
I have my local database instance running on docker. Tested it yesterday with crucial (bare) SQL queries in docker terminal and so far everything was working.

2022-10-30 14:26 UTC, Mario-659 commented
Ok, then I think we should wait until repositories are ready and put it into spring application, not as a separate executable. How about leaving `F1APIJobExecutor.java` on separate branch and not merging it for now. We would merge docker and `.sql` file in this PR. Do you agree? 

When I execute all queries from `init.sql` file on the existing tables made from JPA I get errors about some constrains:

![image](https://user-images.githubusercontent.com/78920002/198883885-c0a93f4e-85c7-4ad4-bb8b-4eb9c5170840.png)

2022-11-02 09:56 UTC, lukaszmichalskii commented
I will check this issue one more time with the master then cherry-pick docker-compose.yml configurations and the `.sql` initialization script. For now abandon F1JobExecutor feature, as clarified first we need to create a complete working API.

2022-11-02 09:56 UTC, closed without merging