Accident service
Mario-659/FormulaOneApi pull request #15
Opened 2022-11-24 14:01 UTC by lukaszmichalskii

2022-11-24 14:03 UTC, lukaszmichalskii commented
Manually tested in Postman, did not implement endpoint unit tests and mocking.

2022-11-24 15:29 UTC, lukaszmichalskii commented
Add constrains on description limit and proper error message, current behavior:
![test](https://user-images.githubusercontent.com/76202883/203820234-6743b63a-27ac-446e-920a-6f607f504437.png)

2022-11-26 22:09 UTC, Mario-659 requested changes
That assertion and exception throw in DELETE is good. 

I added id validation group and `ElementAlreadyExists` exception in team service PR so maybe we could merge my PR, then you can rebase on main and add those small changes with my solutions?

2022-11-26 22:09 UTC, Mario-659 commented on src/main/java/com/formulaoneapi/service/AccidentService.java
> +    }
Post should only create new resource, not update. I think we should return 409 after POST with name already existing. Maybe add `assertAccidentDoesNoExist` method here. Take a look how I solved this in team service PR.

2022-11-26 22:09 UTC, Mario-659 commented on src/main/java/com/formulaoneapi/model/Accident.java
>      private String name;
- add `@Size` to id 
- separate validation from id to a group (see my teams PR), when we are doing PUT we pass name in path, not in body. Valid body in PUT should look like this:
```json
{
    "description": "More informative description"
}
```

2022-11-26 22:09 UTC, Mario-659 commented on src/main/java/com/formulaoneapi/service/AccidentService.java
> +    public void remove(String name) {
add `@Transactional`

2022-11-30 12:05 UTC, lukaszmichalskii commented
Done, check if everything is OK

2022-11-30 18:06 UTC, Mario-659 approved these changes

2022-11-30 18:07 UTC, merged